# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3729f7229abcec124adeed8808666083b084801ae62d36c3ed123fd11d58eb4be59d1e13d878e29e64e0937317f46eaeaaba53e7e4a6e363c56f66658f87f04

test:
  secret_key_base: 7c09746aa407b0dd8b4efb073693c2665f21e175fd79a9ce981644087bd73bcde6c13af350981d4826306cf5d42496730355791b8cda7f20ae1072e5e625275e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
